### ISSUE TITLE
 JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by rutherford** [olejorgenb/ColorNote-backup-decryptor#2]
java -cp colornote-decrypt.jar:bcprov-jdk15on-160.jar ColorNoteBackupDecrypt  0000 28 < 1525831085526-AUTO.doc > notes.json
`java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:130)
        at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:212)
        at ColorNoteBackupDecrypt.init(ColorNoteBackupDecrypt.java:56)
        at ColorNoteBackupDecrypt.main(ColorNoteBackupDecrypt.java:45)
Caused by: java.util.jar.JarException: file:/home/me/colornote-decrypt.jar has unsigned entries - ColorNoteBackupDecrypt.class
        at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
        at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
        at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
        at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
        at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:189)
        at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:215)
        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:127)
        ... 3 more
Exception in thread "main" java.lang.SecurityException: JCE cannot authenticate the provider BC
        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:683)
        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:614)
        at ColorNoteBackupDecrypt.init(ColorNoteBackupDecrypt.java:69)
        at ColorNoteBackupDecrypt.main(ColorNoteBackupDecrypt.java:45)
Caused by: java.util.jar.JarException: file:/home/me/colornote-decrypt.jar has unsigned entries - ColorNoteBackupDecrypt.class
        at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
        at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
        at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
        at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
        at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:189)
        at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:215)
        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:127)
        at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:212)
        at ColorNoteBackupDecrypt.init(ColorNoteBackupDecrypt.java:56)
        ... 1 more
`

**Comment by olejorgenb** [comment]
Interesting.. Seems OpenJDK doesn't very the jars - that's probably why I haven't run into this before. I haven't done anything with the `bcprov-*-154.jar`s that's bundled in colornote-decrypt.jar though, and according to https://stackoverflow.com/questions/13721579/jce-cannot-authenticate-the-provider-bc-in-java-swing-application/13726570#13726570 they should be signed..

**Comment by olejorgenb** [comment]
Hopefully fixed by running the class file directly (see updated README instructions) 

Ref: 90fad0403ad7c38975ee4b6c9b480812d3fc2348 8b585ec8051dcb476c3ff89845651ddf98115ed0

**Comment by olejorgenb** [comment]
The reason the signing did not work inside the jar is that bundling jars inside a jar is not supported out of the box so eclipse will inline the class files when bundling a library... That brakes the signing since it's the bcprov _jar_ files that's signed, not the class files inside.

`HoursLostToSIllyUSEncryptionExportRestrictions++` :angry:
